### PR TITLE
Sign options

### PR DESCRIPTION
**Pull request by awerebea**

### CODE REVIEW

**Comment by wulfgarpro** [comment]
FWIW, I'll merge this as soon as I have some testing in place #15.

**Comment by wulfgarpro** [comment]
`zhps -r $UID -s $UID -y` resulted in command:
`/usr/bin/gpg --yes -v -r "0" --sign --default-key "0" --sign --encrypt --armor --output /root/.zsh_history_proj/zsh_history /root/.zsh_history`.

Should `--sign` by in the command twice?

**Comment by awerebea** [comment]
> Should `--sign` by in the command twice?

That's weird, because I don't have this issue with the same commit:
image

**Comment by awerebea** [comment]
I also checked the code from the `sign-options` branch of the current (origin) repository and it also works as expected:
image
image
So everything seems to be fine and I can't figure out where the second `--sign` came from in your case.

**Comment by wulfgarpro** [comment]
Merged in:

85baf12833a8239d275f94c98a6f01a95823dc48

Bug fix in:

e66cc5a84d15851f2e8a0d2e4b492ed4bc95900d

**Pull request closed without merging**
